### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by raghul2301** [kishorerajan810/Day-21-Prime-Numbers-Python#1]
@kishorerajan810 
is this code show prime numbers?!the code you written only prints even numbers

**Comment by raghul231** [comment]
yeah sure, I will rectify it

**Comment by kishorerajan810** [comment]
yeah sure, I will rectify it

**Comment by kishorerajan810** [comment]
num=int(input("enter :"))
for i in range(2,num):             #Prime number
    if(num%i==0):
        print("not prime")
        break
else:
    print("prime")

I modify my code now just check it.
